### ISSUE TITLE
time.cloudflare.com seems to be ignoring three of every four packets my NTPsec install sends to it.

### ISSUE THREAD

**Issue by JamesB192** [cloudflare/cfnts#44]
expected behavior: the host should reply to all packets sent to it.

observed behavior: the host silently drops 3/4 of packets sent to it.

extra info: The remote host 162.159.200.123 seen from the western US.
packet [captures.zip](https://github.com/cloudflare/cfnts/files/4605345/captures.zip) The effective poll is 64s.

steps
1. send NTS packet with a unique ID, cookie, and AEAD extensions
2. wait for a packet that never arrives
3. send NTS packet with a unique ID, cookie, a cookie placeholder, and AEAD
4. wait for a packet that never arrives
5. send NTS packet with a unique ID, cookie, 2 cookie placeholders, and AEAD
6. wait for a packet that never arrives
7. send NTS packet with a unique ID, cookie, 3 cookie placeholders, and AEAD
4. get back a packet with a unique ID and large AEAD (presumably w/ 4 cookies)
9. repeat

**Comment by wbl** [comment]
Thanks for your report! These are nasty to debug and reproduce, and differentiating from network issues can be tricky, but I'm committed to getting to the bottom of this. First some questions:

1. Which client are you using?
2. Does it affect other NTS hosts?
3. Have you been able to reproduce locally?
4. Could you gather a traceroute or mtr to 162.159.200.123?
5. Does it affect IPv6 as well?

Thank you for attaching the pcap!

**Comment by JamesB192** [comment]
1. I think it is a261794ad3ec81424300f6835417ffa19572033a which is branch tacked on at 6549d0878ff9665e8d34fa500b3e2db51689e40b.

2. It does not affect ntsts.sth.ntp.se.

3. I am not sure how to try to reproduce locally. walkthrough link?

4.  I can try. Did I pass the right arguments to mtr?
```
$ traceroute 162.159.200.123 
traceroute to 162.159.200.123 (162.159.200.123), 30 hops max, 60 byte packets
 1  _gateway (192.168.42.1)  12.017 ms  11.992 ms  11.984 ms
 2  10.117.219.1 (10.117.219.1)  23.764 ms  23.782 ms  23.776 ms
 3  192.168.35.109 (192.168.35.109)  23.770 ms  23.769 ms  23.757 ms
 4  10.224.253.153 (10.224.253.153)  48.199 ms  52.538 ms  52.549 ms
 5  * * *
 6  * * *
 7  4.14.244.230 (4.14.244.230)  55.391 ms  56.135 ms  56.006 ms
 8  time.cloudflare.com (162.159.200.123)  53.887 ms  53.907 ms  58.770 ms
$ mtr -r -c 5 162.159.200.123
Start: 2020-05-10T10:00:41-0700
HOST: taos                        Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- _gateway                   0.0%     5    7.3   6.4   5.4   7.6   1.0
  2.|-- 10.117.219.1               0.0%     5   15.5  16.7  15.2  19.6   1.9
  3.|-- 192.168.35.109             0.0%     5   16.3  19.6  13.6  34.1   8.3
  4.|-- 10.224.253.153             0.0%     5  162.6  65.9  38.6 162.6  54.1
  5.|-- ???                       100.0     5    0.0   0.0   0.0   0.0   0.0
  6.|-- ???                       100.0     5    0.0   0.0   0.0   0.0   0.0
  7.|-- 4.14.244.230               0.0%     5  124.6  71.5  55.7 124.6  29.8
  8.|-- time.cloudflare.com        0.0%     5   60.6  56.5  54.5  60.6   2.4

```

5. I do not have IPv6 on this machine. (upstream will upgrade when no more IPv4 only boxes)

**Comment by JamesB192** [comment]
2a. happens on kong.rellim.com

3a1. local invokation of `sudo ./target/debug/cfnts client -4 time.cloudflare.com` dies after sending an unanswered volley. (from git head)

3a2. invoking `sudo docker-compose up --build` get an instance which works 100% when connected to with noval(idation) of the KE certificate. (from git head)

Huh, starting look like a network/firewall issue somewhere.

**Comment by wbl** [comment]
Thanks for the additional information. It does look like a network issue then: unfortunately lots of networks have trouble with NTS, and it's difficult to figure out why. I can definitely try to improve the robustness of the cfnts client.
